apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-details
  labels:
    app: details
    service: details
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.details.type }}
  selector:
    app: details
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.details.ports | toYaml | nindent 2 }}