apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-reviews
  labels:
    app: reviews
    service: reviews
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reviews.type }}
  selector:
    app: reviews
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.reviews.ports | toYaml | nindent 2 }}