version: '3'

tasks:
  install-dnsmasq:
    cmds:
      - brew install dnsmasq
      - mkdir -pv $(brew --prefix)/etc/
      - echo 'address=/.test/127.0.0.1' >> $(brew --prefix)/etc/dnsmasq.conf
      - echo 'port=53' >> $(brew --prefix)/etc/dnsmasq.conf
      - sudo brew services start dnsmasq
      - sudo mkdir -v /etc/resolver
      - sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/test'

  init-cluster:
    cmds:
      - kind create cluster --config=kind-config.yaml

  install-istio-sidecards:
    cmds:
      - kubectl create ns istio-system --dry-run=client -o yaml | kubectl apply -f-
      - kubectl apply -f sidecards/demo.yaml
      - kubectl apply -f sidecards/ingress-gateway.yaml

  deploy-bookinfo:
    cmds:
      - kubectl apply -n bookinfo -f bookinfo/namespace.yml
      - kubectl apply -n bookinfo -f bookinfo/