version: '3'

tasks:
  install-dnsmasq:
    cmds:
      - brew install dnsmasq
      - mkdir -pv $(brew --prefix)/etc/
      - echo 'address=/.local/127.0.0.1' >> $(brew --prefix)/etc/dnsmasq.conf
      - echo 'port=53' >> $(brew --prefix)/etc/dnsmasq.conf
      - sudo brew services start dnsmasq
      - sudo mkdir -v /etc/resolver
      - sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/local'

  install-sidecars:
    cmds:
      - tofu init
      - tofu apply
    dir: sidecars
    env:
      TF_VAR_bookinfo: true

  install-ambient:
    cmds:
      - tofu apply
    dir: ambient

  install-gateway-crds:
    cmds: 
      - kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.2.0" | kubectl apply -f -; }

  deploy-bookinfo-gw:
    cmds:
      - kubectl apply -f sidecards/k8s-gateway.yaml
      - kubectl -n bookinfo patch svc/bookinfo-gateway-istio --patch-file sidecards/k8s-gateway-patch.json 

  deploy-bookinfo:
    cmds:
      - kubectl apply -n bookinfo -f bookinfo/namespace.yml
      - kubectl apply -n bookinfo -f bookinfo/

  expose-bookinfo:
    cmds:
      - kubectl apply -n bookinfo -f bookinfo/istio/destinationrules.yaml
      - kubectl apply -n bookinfo -f bookinfo/istio/virtualservices-v1.yaml