version: '3'

tasks:
  install-dnsmasq:
    cmds:
      - brew install dnsmasq
      - mkdir -pv $(brew --prefix)/etc/
      - echo 'address=/.local/127.0.0.1' >> $(brew --prefix)/etc/dnsmasq.conf
      - echo 'port=53' >> $(brew --prefix)/etc/dnsmasq.conf
      - sudo brew services start dnsmasq
      - sudo mkdir -v /etc/resolver
      - sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/local'

  init-cluster:
    cmds:
      - kind create cluster --config=kind-config.yaml
  
  install-gateway-crds:
    cmds: 
      - kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.2.0" | kubectl apply -f -; }

  deploy-bookinfo-gw:
    cmds:
      - kubectl apply -f sidecards/k8s-gateway.yaml
      - kubectl -n bookinfo patch svc/bookinfo-gateway-istio --patch-file sidecards/k8s-gateway-patch.json 

  install-istio-sidecards:
    cmds:
      - kubectl create ns istio-system --dry-run=client -o yaml | kubectl apply -f-
      - kubectl apply -f sidecards/demo.yaml
      - kubectl apply -f sidecards/ingress-gateway.yaml

  deploy-bookinfo:
    cmds:
      - kubectl apply -n bookinfo -f bookinfo/namespace.yml
      - kubectl apply -n bookinfo -f bookinfo/
